language: python
python:
  - "3.6"
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libproj-dev
    - libgdal-dev
env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
  matrix:
    - GDALVERSION="2.2.3"
    - GDALVERSION="2.2.4"
before-install:
  - pip install -U pip
  - pip install wheel
  - travis_wait . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
install:
  - "if [ $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
  - pip install -r requirements.txt
script:
  - py.test