language: python
python:
  - "3.6"
cache: pip
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
env:
  global:
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal
install:
  - pip install -r requirements.txt
script:
  - py.test --cov-report term-missing --cov app -v