language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment -c conda-forge python=3.6 numpy gdal geopandas pandas pyproj
  - source activate test-environment
  - pip install pytest==4.2.0
  - pip install pytest-cov==2.5.1
  - pip install coverage==4.0.3
  - pip install python-coveralls==2.9.1
  - python setup.py install
  - conda list -n test-environment
script:
  python -m pytest -v --junitxml=result.xml --cov rastertodataframe --cov-report term-missing
after_success:
  - coveralls