name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=2.2.4=py36_0
  - geopandas=0.3.0=py36_0
  - pandas=0.23.2=py36_0
  - pyproj=1.9.5.1=py36_0
  - pip:
    - coverage==4.5.1
    - flake8==3.5.0
    - sphinx==1.7.1
    - sphinxcontrib-websupport==1.1.0
    - tox==2.9.1
    - twine==1.10.0