name: rastertodataframe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - gdal=2.2.4
  - geopandas=0.3.0
  - pandas=0.23.2
  - pyproj=1.9.5.1
  - numpy=1.14.2
  - pip:
    - coverage==4.5.1
    - flake8==3.5.0
    - sphinx==1.7.1
    - sphinxcontrib-websupport==1.1.0
    - sphinxcontrib-napoleon==0.6.1
    - mock==2.0.0
    - sphinx_rtd_theme==0.4.0
    - twine==1.10.0